### ISSUE TITLE
Step File doesn't show mounting holes

### ISSUE THREAD

**Issue by jscatena88** [myriadrf/LimeSDR-Mini#1]
I am attempting to create a 3d printable case for my new Mini. I downloaded the STEP file for the board and noticed it does not have the two mounting holes up near the USB connector nor the 4 side cutouts. Would it be possible to get a new STEP file that has these in it so I can build my case around them?

**Comment by 9600** [comment]
@ztamosevicius could someone please update the STEP file.

**Comment by ztamosevicius** [comment]
Just updated the repo. Check folder "hardware/1v1" for updated data.
